# Generated by Django 4.2.1 on 2023-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('vtype', models.IntegerField()),
                ('vmodel', models.CharField(max_length=50)),
                ('vdesc', models.CharField(max_length=500)),
            ],
        ),
    ]
